export enum INVALID_CODES {
  ACCOUNT_IS_REQUIRED = "ACCOUNT_IS_REQUIRED",
  PASSWORD_IS_REQUIRED = "PASSWORD_IS_REQUIRED",
  PASSWORD_IS_TOO_SHORT = "PASSWORD_IS_TOO_SHORT",
  USERNAME_IS_REQUIRED = "USERNAME_IS_REQUIRED",
}
