@host = http://localhost:3000/api/auth

###

POST {{host}}/register
Content-Type: application/json

{
    "account": "test1",
    "password": "testtest",
    "username": "test"
}

###

POST {{host}}/login
Content-Type: application/json

{
    "account": "test1",
    "password": "testtest"
}

###

GET {{host}}/5?token=123
Content-Type:application/json

###

GET {{host}}/notfound
Content-Type: application/json

###

GET {{host}}/empty
Content-Type: application/json

###

POST {{host}}/error
Content-Type: application/json

###

GET {{host}}/file
Content-Type: application/json

###

POST {{host}}/file
Content-Type: multipart/form-data; boundary=b

--b
Content-Disposition: form-data; name="file"; filename="test.txt"

< ./assets/test.txt
--b--
